apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokemission
  namespace: pokemission
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /api/mission
            pathType: Prefix
            backend:
              service:
                name: mission-service
                port:
                  number: 8000
          - path: /api/subscriber
            pathType: Prefix
            backend:
              service:
                name: subscriber-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
